### PR TITLE
Small logging fix for DealCluster

### PR DESCRIPTION
**Pull request by amargedon**
Small fix, only cosmetic. But hey, the eye also wants something ;)

### CODE REVIEW

**Comment by cyberjunky** [comment]
This seem overkill, wrong solution, what is this for?

```
enablepairs += "\'" + str(pair) + "\'"
```

**Comment by cyberjunky** [comment]
I mean this is the same?
```
logger.info(
                f"Enabling pairs for cluster {cluster_id}: '{enablepairs}'"
            )
```
Or are the backslashes needed for the db query?

**Comment by amargedon** [comment]
The enable/disable pairs is used in a SQL query, hence the ' required for the 'IN' statement. I also use the enable/disable pairs for logging, and instead of creating it twice (once with, and once without the ' around the pairs) I decided to use one version.

The opening and closing ' was added somewhere below in the code, which is not that consistent because the string is created here. So I decided to move it so it's at one place. 

If there is a simple python function to parse a string and add the required ' around each pair, let me know because that would make this appending unnecessary.

**Comment by cyberjunky** [comment]
Is het niet gewoon mogelijk een list te gebruiken (niet getest)

```
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> disablepair = []
>>> disablepair.append("BTC")
>>> disablepair.append("SOL")
>>> disablepair.append("ETH")
>>> print(disablepair)
['BTC', 'SOL', 'ETH']
```
Dan heb je maar 2 regels nodig:
```
disablepair = []
disablepair.append(pair)
```

**Comment by amargedon** [comment]
Hmm, that looks promising. Will test later and replace!

**Comment by amargedon** [comment]
Opened pull request #76 with the required changes.

**Pull request merged**
